apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kbvwnotyq-go 
  janus-idp.io/tekton: kbvwnotyq-go
  backstage.io/kubernetes-id: kbvwnotyq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kbvwnotyq-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  