apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kbvwnotyq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kbvwnotyq-go 
  name: kbvwnotyq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kbvwnotyq-go 
